image: bradrydzewski/scala:2.10.3
env:
  - GOPATH=/var/cache/drone
script:
  - pwd
  - mvn clean install
  - ls
  - cd target/
  - ls
notify:
  email:
    recipients:
      - manuel.maldonado@verizon.com
