image: bradrydzewski/scala:2.10.3
env:
  - GOPATH=/var/cache/drone
script:
  - mvn clean install
notify:
  email:
    recipients:
      - manuel.maldonado@verizon.com

publish:
  docker:
    docker_host: $$docker_host
    docker_version: $$docker_version
    registry_login: $$registry_login
    username: $$username
    password: $$password
    email: $$email
    image_name: $$username/dronetest
    push_latest: true
    keep_builds: false
    tag: 0.1
