image: bradrydzewski/java:openjdk7
env:
  - GOPATH=/var/cache/drone
script:
  - pwd
  - mvn clean install
notify:
  email:
    recipients:
      - manuel.maldonado@verizon.com
publish:
    docker:
        dockerfile: Dockerfile
        docker_host: {{docker_host}}
        docker_port: {{docker_post}}
        docker_version: {{docker_version}}
        registry_login_url: https://docker-registry.example.com/v1/
        registry_login: true
        username: {{username}}
        password: {{password}}
        email: {{email}}
        image_name: {{username}}/dronetest
        push_latest: true
        keep_builds: false
        tag: 0.1
