image: phusion/baseimage
env:
  - GOPATH=/var/cache/drone
  - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
notify:
  email:
    recipients:
      - manuel.maldonado@verizon.com
      - manuel.maldonado@verizon.com
